// Cart
export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const UPDATE_ITEM = "UPDATE_ITEM";
export const UPDATE_CART_TOTAL = "UPDATE_CART_TOTAL";
export const REMOVE_ITEM_IN_CART = "REMOVE_ITEM_IN_CART";
export const UPDATE_APPLICATED_OFFER = "UPDATE_APPLICATED_OFFER";
export const RESET_CART_TOTAL = "RESET_CART_TOTAL";
export const INJECT_CART = "INJECT_CART";
export const RESET_CART = "RESET_CART";

// App
export const ADD_ALL_ITEMS = "ADD_ALL_ITEMS";
export const UPDATE_LOCALE = "UPDATE_LOCALE";
export const UPDATE_SCREEN_SIZE = "UPDATE_SCREEN_SIZE";
export const UPDATE_HOME_POSITION = "UPDATE_HOME_POSITION";
